version: "3.7"
services:
  web:
    build:
      context: app
      target: builder
    stop_signal: SIGINT
    env_file: .env
    networks:
      - docker_proxy
      - db
    volumes:
      - ./app:/app
      - /etc/localtime:/etc/localtime:ro

networks:
  docker_proxy:
    external: true  
  db:

volumes:
  cache:
